[package]
name = "shape"
version = "0.1.0"
authors = ["wengrs <flower_be_forever@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base = { path = "../base"}